# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tomek/Pulpit/pobr

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tomek/Pulpit/pobr

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tomek/Pulpit/pobr/CMakeFiles /home/tomek/Pulpit/pobr/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tomek/Pulpit/pobr/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pobr

# Build rule for target.
pobr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pobr
.PHONY : pobr

# fast build rule for target.
pobr/fast:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/build
.PHONY : pobr/fast

src/action.o: src/action.cpp.o

.PHONY : src/action.o

# target to build an object file
src/action.cpp.o:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/action.cpp.o
.PHONY : src/action.cpp.o

src/action.i: src/action.cpp.i

.PHONY : src/action.i

# target to preprocess a source file
src/action.cpp.i:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/action.cpp.i
.PHONY : src/action.cpp.i

src/action.s: src/action.cpp.s

.PHONY : src/action.s

# target to generate assembly for a file
src/action.cpp.s:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/action.cpp.s
.PHONY : src/action.cpp.s

src/base.o: src/base.cpp.o

.PHONY : src/base.o

# target to build an object file
src/base.cpp.o:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/base.cpp.o
.PHONY : src/base.cpp.o

src/base.i: src/base.cpp.i

.PHONY : src/base.i

# target to preprocess a source file
src/base.cpp.i:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/base.cpp.i
.PHONY : src/base.cpp.i

src/base.s: src/base.cpp.s

.PHONY : src/base.s

# target to generate assembly for a file
src/base.cpp.s:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/base.cpp.s
.PHONY : src/base.cpp.s

src/calibrationclass.o: src/calibrationclass.cpp.o

.PHONY : src/calibrationclass.o

# target to build an object file
src/calibrationclass.cpp.o:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/calibrationclass.cpp.o
.PHONY : src/calibrationclass.cpp.o

src/calibrationclass.i: src/calibrationclass.cpp.i

.PHONY : src/calibrationclass.i

# target to preprocess a source file
src/calibrationclass.cpp.i:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/calibrationclass.cpp.i
.PHONY : src/calibrationclass.cpp.i

src/calibrationclass.s: src/calibrationclass.cpp.s

.PHONY : src/calibrationclass.s

# target to generate assembly for a file
src/calibrationclass.cpp.s:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/calibrationclass.cpp.s
.PHONY : src/calibrationclass.cpp.s

src/classifier.o: src/classifier.cpp.o

.PHONY : src/classifier.o

# target to build an object file
src/classifier.cpp.o:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/classifier.cpp.o
.PHONY : src/classifier.cpp.o

src/classifier.i: src/classifier.cpp.i

.PHONY : src/classifier.i

# target to preprocess a source file
src/classifier.cpp.i:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/classifier.cpp.i
.PHONY : src/classifier.cpp.i

src/classifier.s: src/classifier.cpp.s

.PHONY : src/classifier.s

# target to generate assembly for a file
src/classifier.cpp.s:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/classifier.cpp.s
.PHONY : src/classifier.cpp.s

src/element.o: src/element.cpp.o

.PHONY : src/element.o

# target to build an object file
src/element.cpp.o:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/element.cpp.o
.PHONY : src/element.cpp.o

src/element.i: src/element.cpp.i

.PHONY : src/element.i

# target to preprocess a source file
src/element.cpp.i:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/element.cpp.i
.PHONY : src/element.cpp.i

src/element.s: src/element.cpp.s

.PHONY : src/element.s

# target to generate assembly for a file
src/element.cpp.s:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/element.cpp.s
.PHONY : src/element.cpp.s

src/elementgetter.o: src/elementgetter.cpp.o

.PHONY : src/elementgetter.o

# target to build an object file
src/elementgetter.cpp.o:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/elementgetter.cpp.o
.PHONY : src/elementgetter.cpp.o

src/elementgetter.i: src/elementgetter.cpp.i

.PHONY : src/elementgetter.i

# target to preprocess a source file
src/elementgetter.cpp.i:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/elementgetter.cpp.i
.PHONY : src/elementgetter.cpp.i

src/elementgetter.s: src/elementgetter.cpp.s

.PHONY : src/elementgetter.s

# target to generate assembly for a file
src/elementgetter.cpp.s:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/elementgetter.cpp.s
.PHONY : src/elementgetter.cpp.s

src/imagewrapper.o: src/imagewrapper.cpp.o

.PHONY : src/imagewrapper.o

# target to build an object file
src/imagewrapper.cpp.o:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/imagewrapper.cpp.o
.PHONY : src/imagewrapper.cpp.o

src/imagewrapper.i: src/imagewrapper.cpp.i

.PHONY : src/imagewrapper.i

# target to preprocess a source file
src/imagewrapper.cpp.i:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/imagewrapper.cpp.i
.PHONY : src/imagewrapper.cpp.i

src/imagewrapper.s: src/imagewrapper.cpp.s

.PHONY : src/imagewrapper.s

# target to generate assembly for a file
src/imagewrapper.cpp.s:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/imagewrapper.cpp.s
.PHONY : src/imagewrapper.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/segmentation.o: src/segmentation.cpp.o

.PHONY : src/segmentation.o

# target to build an object file
src/segmentation.cpp.o:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/segmentation.cpp.o
.PHONY : src/segmentation.cpp.o

src/segmentation.i: src/segmentation.cpp.i

.PHONY : src/segmentation.i

# target to preprocess a source file
src/segmentation.cpp.i:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/segmentation.cpp.i
.PHONY : src/segmentation.cpp.i

src/segmentation.s: src/segmentation.cpp.s

.PHONY : src/segmentation.s

# target to generate assembly for a file
src/segmentation.cpp.s:
	$(MAKE) -f CMakeFiles/pobr.dir/build.make CMakeFiles/pobr.dir/src/segmentation.cpp.s
.PHONY : src/segmentation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pobr"
	@echo "... src/action.o"
	@echo "... src/action.i"
	@echo "... src/action.s"
	@echo "... src/base.o"
	@echo "... src/base.i"
	@echo "... src/base.s"
	@echo "... src/calibrationclass.o"
	@echo "... src/calibrationclass.i"
	@echo "... src/calibrationclass.s"
	@echo "... src/classifier.o"
	@echo "... src/classifier.i"
	@echo "... src/classifier.s"
	@echo "... src/element.o"
	@echo "... src/element.i"
	@echo "... src/element.s"
	@echo "... src/elementgetter.o"
	@echo "... src/elementgetter.i"
	@echo "... src/elementgetter.s"
	@echo "... src/imagewrapper.o"
	@echo "... src/imagewrapper.i"
	@echo "... src/imagewrapper.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/segmentation.o"
	@echo "... src/segmentation.i"
	@echo "... src/segmentation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

